feature: testing lighthouse-ci in circle config
OhanaCoursework/OhanaHomes pull request #33
Opened 2023-04-24 18:45 UTC by gillo17

# Description

PR to add performance tests as apart of the ci/cd pipeline

# Jira Ticket

Please add a link to the related Jira ticket
Please also add a link to this PR in the Jira ticket

# Checklist

These are the items (excluding github checks) that should be confirmed before a branch us ready to merge

- [ ] Acceptance Criteria met
- [ ] Code has been self-reviewed and manually tested
- [ ] Added tests that prove my fix is effective and that my feature is working
- [ ] Ran accessibilty tests
- [ ] Test coverage of new code meets 80%
- [ ] Added / updated any relevant documentation

2023-04-25 15:37 UTC, darciegrace approved these changes

2023-04-26 23:39 UTC, kman8887 requested changes

2023-04-26 23:39 UTC, kman8887 commented on src/generalComponents/navbar/Navbar.js
> +        <Link aria-label="Link to the home page" o="/">
to not o

2023-04-26 23:39 UTC, declanlarkin2 approved these changes

2023-04-27 20:26 UTC, kman8887 approved these changes

2023-04-27 20:27 UTC, merged